### ISSUE TITLE
Replace full history table with audit log

### ISSUE THREAD

**Issue by vinayakh** [klpdotorg/tada#1]
The fullhistory table is not useful today as much as it can be. In case of problems an audit log can be grepped to find issues. Also the fullhistory tables does not give an easy way to revert changes to the db. Taking this into account, we should convert this to an audit log that can be archived to s3. Also the current implementation shoves json data into the DB which is always a bad idea.

**Comment by harisibrahimkv** [comment]
Used https://github.com/soynatan/django-easy-audit.
