### ISSUE TITLE
Model definition on Wiki

### ISSUE THREAD

**Issue by meghaklp** [klpdotorg/tada#10]
Do you want to add the columns/attributes maybe?

Also partitioning has some logic. I'm just keeping it here as an FYI:

`Description of Partitioning of Tables in KLP schema

These following tables were selected for Partitioning due to their large volume
1. Answer
   The Answer table is partitioned based on the field 'question_id'.
   Each partition has constraint to accept records of every 50 values of 'question_id'.
   Eg.,'question_id' 0-49 is stored in Partition 0, 'question_id' 50-99 is stored in Partition 1,….etc.
   Due to nature of the fields dynamism, the PGSQL Trigger has been set to create new partitions dynamically.
2. Assessment_Studentgroup_Association
   The Assessment_Studentgroup_Association table is partitioned based on the field 'active'.
   Since 'active' takes only three values(0, 1, 2), Three Static partitions has been set.
3. Child
   The Child table is partitioned based on the field 'id'.
   Each partition has constraint to accept records of every 200000 values of 'id'.
   Eg., 'id' 0-199999 is stored in Partition 0, 'id' 200000- 399999 is stored in Partition 1,….etc.
   Due to nature of the fields dynamism, the PGSQL Trigger has been set to create new partitions dynamically.
4. Relations
   The Relations table is partitioned based on the field 'id'.
   Each partition has constraint to accept records of every 200000 values of 'id'.
   Eg.,'id' 0-199999 is stored in Partition 0, 'id' 200000- 399999 is stored in Partition 1,….etc.
   Due to nature of the fields dynamism, the PGSQL Trigger has been set to create new partitions dynamically.
5. Student
   The Student table is partitioned based on the field 'active'.
   Since 'active' takes only three values(0, 1, 2), Three Static partitions has been set.
6. StudentGroup
   The StudentGroup table is partitioned based on the field 'active'.
   Since 'active' takes only three values(0, 1, 2), Three Static partitions has been set.
7. Student_StudentGroupRelation
   The Student_StudentGroupRelation table is partitioned based on the field 'active'.
   Since 'active' takes only three values(0, 1, 2), Three Static partitions has been set.
8. UserAssessmentPermissions
   The UserAssessmentPermissions table is partitioned based on the field 'user_id'.
   Eg., 'user_id' 60  is stored in Partition 60,  'user_id' 81 is stored in Partition 81,….etc.
   Due to nature of the fields dynamism, the PGSQL Trigger has been set to create new partitions dynamically.`

**Comment by vinayakh** [comment]
All inputs incorporated in the new model.
