### ISSUE TITLE
Double entry implementation using staging table

### ISSUE THREAD

**Issue by vinayakh** [klpdotorg/tada#11]
Documenting the discussion between me and @batpad to simplify the double entry.

Currently the first entry and the double entry are both in the same table so this DB design leads to issues because partial unverified entries reside in the same table and may be orphaned. This also marked queries complex and table bulkier. 

A simpler approach would be to 'hold' single unverified entries in a 'staging' table. This would ensure that the queries become simple and merging on double verification becomes easier. So the algorithm would be some thing like this:
1. If this is a first entry, then make an entry in the staging table and leave it there.
2. When the time for double entry comes, check the staging table.
3. If the entries match 
    then delete the entries in staging table and move those entries to the finalized table. Also the finalized table will have all the metadata about both the entries.
   else prompt the user to check the entries. After the user corrects the entries then save the new entries in the new table and delete the entries in the old table.

This approach 
1. Makes the queries simpler as only one table is queried at a time.
2. Requires no filtering and each table can be indexed separately.
3. Leaves no orphaned entries in the main table.
4. Makes both tables smaller due to separation of concerns

**Comment by vinayakh** [comment]
More info on double entry.
http://trac.klp.org.in/wiki/KLPNewMIS#Assessments
http://trac.klp.org.in/wiki/DoubleEntry

**Comment by harisibrahimkv** [comment]
We decided to do away with the temp holding table and just use the `double_entry` flag to keep track of whether it is the first time or the second time an answer is being entered.
