### ISSUE TITLE
Mixin for updated_at and created_at times for DEO Billing and audit trail

### ISSUE THREAD

**Issue by vinayakh** [klpdotorg/tada#12]
A great idea that came up while brainstorming with @batpad. We were thinking how do we get rid of the audit trail while retaining it's usefulness for verification and billing especially for paying DEOs.

We can created a mixin that adds created_at and updated_at flags to every model we want. This will enable db examination and verification for most models. Also we will have control over which models need this without making custom changes for everyone..

**Comment by harisibrahimkv** [comment]
We can get this info from the CRUDEvent model used by https://github.com/soynatan/django-easy-audit.
