### ISSUE TITLE
Create proper branches in git

### ISSUE THREAD

**Issue by batpad** [klpdotorg/tada#15]
Create a develop branch to work in and master which should always reflect the state of production. Can continue working in master for now while we get the basic setups sorted, but should soon create branches.

Do we want to use Git Flow? http://nvie.com/posts/a-successful-git-branching-model/ and a little command line tool to help: https://github.com/nvie/gitflow

**Comment by vinayakh** [comment]
Done now committing to a branch and then merging regularly to avoid conflicts. Instead of develop, creating features/stage specific branches. Will have the develop branch when we move to the API development.
