### ISSUE TITLE
Audit log

### ISSUE THREAD

**Issue by vinayakh** [klpdotorg/tada#21]
## Some comments on implementation of Audit Log.
1. One of the ways to implement audit log is https://github.com/Atomidata/django-audit-log
2. Another way is to implement custom post-save method hooks to save the audit log table. 
3. Also the audit log should in db and not in a file to help querying and reduce moving parts
4. We should run a cronjob to cull the audit log every month or archive it.
## Minimum set of fields in audit log
1. Entity Name
2. Entity Id
3. Timestamp
4. User
5. Type of Action
6. Score (+1/-1)
### A. Single entry

Just add the above fields in a row and you are done
### B. Double Entry

When user 1 makes the first entry add a +1 with all other details as above
When user 2 makes an entry
     If "Correct" then add another entry for user 2 with +1 and save
     If "Incorrect" then add two entries +1 for user 2 and a -1 for user 1

**Comment by harisibrahimkv** [comment]
We've used https://github.com/soynatan/django-easy-audit. `Correct`, `Incorrect`, `Verified` and `Rectified` are not stored as such. Instead, we are storing the history of each object. We will calculate the report from that.
