### ISSUE TITLE
Unify permissions and clean it up

### ISSUE THREAD

**Issue by vinayakh** [klpdotorg/tada#3]
Currently permissions are spread over different tables. It should be revisited and the permissions can be made more granular. Need to rethink the whole permissions bit

**Comment by vinayakh** [comment]
@gkjohn @batpad First Survey here. Please validate (https://github.com/klpdotorg/tada/wiki/User-Permissions-Model)

**Comment by harisibrahimkv** [comment]
Permissions have been implemented using DRF's permission views + https://github.com/django-guardian/.
