### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by batpad** [klpdotorg/tada#42]

**Comment by subhaklp** [comment]
@harisibrahimkv , is this something you can get to real quick? My REST calls from the front-end are failing with "No Access-Control-Allow-Origin header present". This will block further prototyping in the UI.

**Comment by batpad** [comment]
This is the django package we used on dubdubdub and I think DISE: https://github.com/ottoyiu/django-cors-headers

@harisibrahimkv please poke me or @iambibhas if you have any issues setting up. I'm not _sure_ if it needs some config on the webserver end as well - if it does, you would need to figure out what nginx needs, but I think it may not need that and just adding this to django _should_ do it.

**Comment by subhaklp** [comment]
I think we want to do CORS_ORIGIN_ALLOW_ALL = True so we can test from our dev boxes. Eventually, on the server we want to limit this to a select list of hosts. @batpad please confirm.

**Comment by subhaklp** [comment]
@harisibrahimkv I added the CORS package to the requirements file and made a few changes to the settings file to enable support for now. Seems to be working on my local dev machine. I'll push what I have. Maybe you can review it.

**Comment by harisibrahimkv** [comment]
Fixed via https://github.com/klpdotorg/tada/commit/9d5697e5f4e87336027ef15b2289fe6df203548c
