### ISSUE TITLE
Adding logging for compensation for DEOs

### ISSUE THREAD

**Issue by vinayakh** [klpdotorg/tada#48]
For each API action that add an entry to the database (eg. students, schools, preschools, assessments, district, block, cluster, boundary etc), there should be an entry created in the logging table with several parameters as noted in the wiki. This will be used weekly to compensate the DEOs in various centers.

More info at https://github.com/klpdotorg/tada/wiki/Double-Entry-for-Answers (see point 3)

**Comment by harisibrahimkv** [comment]
Audit log is enabled for `Institution`, `Student`, `Staff`, `AnswerStudent`, `AnswerInstitution` and `AnswerStudentGroup` models. Seems like that is we require to create a report like https://github.com/klpdotorg/tada_ui/blob/master/workflow_mockups/summary_file.csv.

**Comment by harisibrahimkv** [comment]
@meghaklp Please take a quick look?

**Comment by meghaklp** [comment]
@harisibrahimkv - looks good
